### ISSUE TITLE
DotNetCore 3 support?

### ISSUE THREAD

**Issue by TheDevelolper** [CloudNimble/ElectronNET.Blazor#4]
Hey, I was just wondering if there was support for .NET core 3?

I tried setting up a project and getting this running but it didn't seem to launch.

**Comment by robertmclaws** [comment]
Hello! Thanks for your interest. Just wanted to let you know that Microsoft fixed the underlying issues that made this necessary, so you can safely remove it from your project and map everything the way the default Blazor template does.

I'll work to update all of our materials shortly. Thanks for your interest, and good luck with your project! Thanks!
